### PR TITLE
Don't follow an already processed relationship.

### LINKED ISSUE #111: Bidirectional relationships lead to a stack overflow error in the Cypher generator.
The following mapping:

```
import java.util.HashSet;
import java.util.Set;

import org.neo4j.springframework.data.core.schema.GeneratedValue;
import org.neo4j.springframework.data.core.schema.Id;
import org.neo4j.springframework.data.core.schema.Node;
import org.neo4j.springframework.data.core.schema.Relationship;

@Node
public class UserEntity {

	@Id @GeneratedValue
	private Long id;

	@Relationship("HAS_PERSISTENT_TOKEN")
	private Set<TokenEntity> persistentTokens = new HashSet<>();
}

@Node
public class TokenEntity {

	@Id @GeneratedValue
	private Long id;

	private UserEntity user;
}
```

Will cause a stack overflow exception in `org.neo4j.springframework.data.core.schema.CypherGenerator#generateListsOf` starting  here `org.neo4j.springframework.data.core.schema.CypherGenerator#projectAllPropertiesAndRelationships`.

### PR DESCRIPTION
**Pull request by meistermeier**
If there is bi-directional mapping in the entities
the Cypher creation wants to eagerly process every path.
This leads to infinite loops that end up in StackOverflows.

Break the cycle by introducing Set that keeps track of the already
visited RelationshipDescriptions.

Closes #111

### CODE REVIEW

File: spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/mapping/DefaultRelationshipDescription.java [hunk 1]
```diff
@@ -126,6 +128,19 @@ public boolean equals(Object o) {
 			&& direction.equals(that.direction);
 	}
 
+	public boolean isInverseOf(RelationshipDescription inverse) {
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/mapping/DefaultRelationshipDescription.java]: I like this.

File: spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/schema/CypherGenerator.java [hunk 2]
```diff
@@ -329,5 +348,16 @@ private MapProjection projectPropertiesAndRelationships(NodeDescription<?> nodeD
 	private static Condition conditionOrNoCondition(@Nullable Condition condition) {
 		return condition == null ? Conditions.noCondition() : condition;
 	}
+
+	private boolean hasInverse(RelationshipDescription relationshipDescription,
+		Collection<RelationshipDescription> relationships) {
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/schema/CypherGenerator.java]: Please rename `relationships` to `processedRelationships`.

I wonder if we could avoid the loop somehow with a `contains`.

File: spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/BidirectionalEndRepository.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+ */
+package org.neo4j.springframework.data.integration.imperative;
+
+import org.neo4j.springframework.data.integration.shared.BidirectionalEnd;
+import org.neo4j.springframework.data.repository.Neo4jRepository;
+
+/**
+ * @author Gerrit Meier
+ */
+public interface BidirectionalEndRepository extends Neo4jRepository<BidirectionalEnd, Long> {
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/BidirectionalEndRepository.java]: Yes, I'm crying a bit about that ("Bidi…"), too.

**Comment by michael-simons** [comment]
Could you add a test for this scenario, please:

```
@Node
public class UserEntity {

	@Id @GeneratedValue
	private Long id;

	@Relationship("HAS_PERSISTENT_TOKEN")
	private Set<TokenEntity> persistentTokens = new HashSet<>();
}

@Node
public class TokenEntity {

	@Id @GeneratedValue
	private Long id;

        @Relationship("SOMETHING_ELSE")
	private UserEntity user;
}
```

?
