### PR TITLE
Fail on start if required id property is missing.

### LINKED ISSUE #224: Null pointer exception is being thrown in org.neo4j.springframework.data.repository.event.IdPopulator
A null pointer is being thrown in `org.neo4j.springframework.data.repository.event.IdPopulator` on row 55. 
```
		Neo4jPersistentEntity<?> nodeDescription = neo4jMappingContext.getRequiredPersistentEntity(entity.getClass());
		IdDescription idDescription = nodeDescription.getIdDescription();

		// Filter in two steps to avoid unnecessary object creation.
                if (!idDescription.isExternallyGeneratedId()) {    // <---- NULL POINTER PART		
			return entity;
		}
```
`getIdDescription()` method is marked @Nullable and I guess somehow null check should exist not to lose the debug info if there is a problem.

Code to reproduce:
```
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Node
@Accessors(chain = true)
public abstract class BaseEntity {

    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;

    @CreatedDate
    private LocalDateTime created;

    @LastModifiedDate
    private LocalDateTime updated;

    @Property(name = "deleted")
    private LocalDateTime deleted;

    BaseEntity(final LocalDateTime created) {
        this.created = created;
        this.updated = created;
    }
}
```
```
@Getter
@Setter
@Accessors(chain = true)
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Node(primaryLabel = "A")
public class A extends BaseEntity {

    @Property("something")
    private String something;

    private Information information;

    public A(final LocalDateTime created) {
        super(created);
    }
}
```
```
@Data
@Accessors(chain = true)
public class Information {

    @Relationship("HAS_REL_1")
    private SomeNode1 rel1; // Type does not make sense here

    @Relationship("HAS_REL_2")
    private SomeNode2 rel2;  // Type does not make sense here
}
```
I already understood that I cannot group the relationships in the wrapper class :)
There is no Id in "Information" class that is why there is a null pointer exception
But I guess the exception should be informative.
I just found it debugging your codes.

P.S. Please write documentation about how to use dynamic relationships and about relationship properties.

### PR DESCRIPTION
**Pull request by meistermeier**
If a class is annotated with `@Node` we can assume that it is the intention of the user to map this entity later. This will mark the entity as an explicit entity and we could apply stricter verification if needed.
This PR uses this mechanism for throwing an exception if the id property is missing.

closes #224

### CODE REVIEW

File: spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/mapping/DefaultNeo4jPersistentEntity.java [hunk 1]
```diff
@@ -56,26 +56,35 @@
...
+	 * that should get validated more strictly.
+	 */
+	private final Boolean isExplicitEntity;
+
+	/**
+	 * The label that describes the label most concrete.
+	 */
 	private final String primaryLabel;
 
+	private final Lazy<List<String>> additionalLabels;
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/mapping/DefaultNeo4jPersistentEntity.java:70]: Nice reordering. I like 👍
