### PR TITLE
Converting reader with relationship properties

### LINKED ISSUE #47: Add support for rich relationships.
Properties on relationships are not yet mappable.

Suggested solution:

* Allow `org.neo4j.springframework.data.core.schema.Relationship` also on `Element.TYPE`
* Fail bootstrap when a class annotated with `@Relationship` is the element of a repository
* Also don't allow querying them with the yet to be defined template later
* The class annotated with `@Node` is the owner of the relationship.
* The class annotated that should be treated as the rich relationship _must_ be annotated with `@Relationship`
* The owning end of the relationship can be annotated with `Relationship`
* If one of possible two annotations has a non default `type` attribute, that shall be the type of the relationship
* If both have a non default `type` attribute, bootstrapping shall fail
* The inverse side of the relationship of the attribute in owning end _must_ be specified with `inverse` attribute in `@Relationship` on the owning attribute
* The type annotated with `@Relationship` will not contain both ends of the relationship
* No attribute inside the type annotated with `@Relationship` must be annotated with `@Relationship`, bootstrap shall fail in such cases.

### PR DESCRIPTION
**Pull request by meistermeier**
This PR will fix #47 and as a consequent introduce migration from mapping function centric entity creation to a converter one.

The creation of the `IdGenerator`s will now take place during runtime instead of startup because the `Neo4jMappingContext` must not be of type `BeanDefinitionRegistryPostProcessor` if the driver gets injected. This would make the `Driver` bean not eligible for `ConfigurationProperties` processing anymore because it would get requested to early in the bean creation process.

### CODE REVIEW

File: spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/reactive/ReactiveRepositoryIT.java [hunk 1]
```diff
@@ -379,6 +383,167 @@ void loadEntityWithRelationshipWithAssignedId() {
...
+				rel2.setPoint(new CartesianPoint2d(2d, 3d));
+
+				assertThat(person.getHobbies()).contains(MapEntry.entry(hobby1, rel1), MapEntry.entry(hobby2, rel2));
+			})
+			.verifyComplete();
+
+	}
+
+
+//	@Test
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/reactive/ReactiveRepositoryIT.java]: Why comments?

**Comment by optama** [comment]
Is there any documentation for this? Specifically regarding properties on relationships.

**Comment by meistermeier** [comment]
I created a new issue for this.
