### PR TITLE
Fix same type bidirectional save.

### LINKED ISSUE #119: Persisting self reference relationship with both directions leads to missing relationship in DB
Hoi,

unfortunately, I think I found a bug when trying to persist the following type of relationship:

```Java
public class Hobby {
	@Id @GeneratedValue private Long id;
	private String name;

	/**
	 * Test if reverse relationship to same node type get persisted correctly.
	 */
	@Relationship(type = "SimilarTo", inverse = "similarHobbyOf")
	private Hobby similarHobby;

	@Relationship(type = "SimilarTo", direction = Relationship.Direction.INCOMING)
	private Hobby similarHobbyOf;	

	// included to ensure empty relationships do not cause deletion
	@Relationship("EmptyRelationship")
	private List<Hobby> noHobbies;
       
// remaining class omitted
}
```
I would expect the following persistence result:
image

Unfortunately I see this result (Note the missing `SimilarTo` relationship on the bottom right):
image

A reproducer test can be found here: https://github.com/thePhil/sdn-rx/blob/0db4928db32d8128d8020f5ea7f24bb8ded316f9/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryIT.java#L547 

The code in #113 also still fails the test, not sure if the resolve of #117 would also fix this bug.

### PR DESCRIPTION
**Pull request by meistermeier**
Due to the processing of self-references on both sides
the relationship may get deleted from the later iteration
after it was created before.
This bug fix prevents the multiple processing of the very same
relationship.

closes #119

### CODE REVIEW

File: spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/ReactiveNeo4jTemplate.java [hunk 1]
```diff
@@ -404,6 +423,13 @@ public ReactiveNeo4jTemplate(ReactiveNeo4jClient neo4jClient, Neo4jMappingContex
 		});
 	}
 
+	private boolean hasProcessed(Set<RelationshipDescription> relationshipDescriptions, RelationshipDescription rd) {
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/ReactiveNeo4jTemplate.java]: I still don't like the parameter name.

File: spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryIT.java [hunk 2]
```diff
@@ -127,6 +129,7 @@ static PersonWithAllConstructor personExample(String sameValue) {
 		this.driver = driver;
 		this.bidirectionalStartRepository = bidirectionalStartRepository;
 		this.bidirectionalEndRepository = bidirectionalEndRepository;
+		this.similarThingRepository = similarThingRepository;
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryIT.java]: I do love that name however.

File: spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryWithADifferentDatabaseIT.java [hunk 3]
```diff
@@ -48,9 +48,11 @@
 		PetRepository petRepository, Driver driver,
 		PersonWithRelationshipWithPropertiesRepository relationshipWithPropertiesRepository,
 		BidirectionalStartRepository bidirectionalStartRepository,
-		BidirectionalEndRepository bidirectionalEndRepository) {
```
Comment (michael-simons) [inline spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryWithADifferentDatabaseIT.java]: We should make a note to drop c'tor injection here and just inject the fields… Or on the methods, but this looks horrible.

Comment (michael-simons) [reply spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryWithADifferentDatabaseIT.java]: And I know I did this.
